Player.create({first_name: 'Steve', last_name: 'Craig', email: 'steve.craig@getg5.com' })
Player.create({first_name: 'Levi', last_name: 'Brown', email: 'levi.brown@getg5.com' })
Player.create({first_name: 'Michael', last_name: 'Mitchell', email: 'michael.mitchell@getg5.com' })
Player.create({first_name: 'Matt', last_name: 'Bishop', email: 'matt.bishop@getg5.com' })
Player.create({first_name: 'Matt', last_name: 'Bishop', email: 'matt.bishop@getg5.com' })